version: '3'

services:

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apache1
      - apache2

  apache1:
    image: httpd:latest
    container_name: apache1
    volumes:
      - ./site1:/usr/local/apache2/htdocs/

  apache2:
    image: httpd:latest
    container_name: apache2
    volumes:
      - ./site2:/usr/local/apache2/htdocs/
